apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: helm-controller
      namespace: default
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/l0g8r8j6/fluxcd/helm-controller:v0.37.4-eks-a-v0.20.0-dev-build.110
            name: manager
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kustomize-controller
      namespace: default
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/l0g8r8j6/fluxcd/kustomize-controller:v1.2.2-eks-a-v0.20.0-dev-build.110
            name: manager
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: notification-controller
      namespace: default
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/l0g8r8j6/fluxcd/notification-controller:v1.2.4-eks-a-v0.20.0-dev-build.110
            name: manager
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: source-controller
      namespace: default
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/l0g8r8j6/fluxcd/source-controller:v1.2.4-eks-a-v0.20.0-dev-build.110
            name: manager
